config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains
  root 'railway_stations#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
	validates :title, presence: true

	has_many :trains
	has_many :railway_stations_routes
	has_many :routes, through: :railway_stations_routes
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
	belongs_to :railway_station
	belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
	has_many :railway_stations_routes
	has_many :railway_stations, through: :railway_stations_routes
end

app/models/train.rb
class Train < ApplicationRecord
	validates :number, presence: true
	belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController

	before_action :set_train, only: [:show, :edit, :update, :destroy]

	def index
		@trains = Train.all
	end

	def show
	end

	def new
		@train = Train.new
	end

	def create
		@train = Train.new(train_params)

		if @train.save
			redirect_to @train
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @train.update(train_params)
			redirect_to @train
		else
			render 'edit'
		end
	end

	def destroy
		@train.destroy
		redirect_to trains_path
	end

	private

	def set_train
		@train = Train.find(params[:id])
	end

	def train_params
		params.require(:train).permit(:number, :current_station_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/common/_errors.html.erb
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>
<%= render 'common/errors', resource: @railway_station %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Железнодорожные станции</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Показать', railway_station %></td>
        <td><%= link_to 'Изменить', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить станцию', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
<p>Станция не входит ни в один маршрут</p>
<% else %>
<p>Станция входит в следующие маршруты</p>
<ul>
	<% @railway_station.routes.each do |route| %>
	<li><%= route.name %></li>
	<% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <%= render 'common/errors', resource: @train %>
  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
	
	<div class="field">
		<%= f.label :current_station, "Текущая станция" %>
		<%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
	</div>

  <div class="actions">
    <%= f.submit "#{ @train.new_record? ? 'Добавить' : 'Изменить' }" %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Показать', train %></td>
        <td><%= link_to 'Изменить', edit_train_path(train) %></td>
        <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_train_path %>

app/views/trains/new.html.erb
<h1>Добавить поезд</h1>
<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Номер:</strong>
	<%= @train.number %>
</p>

<p>
	<% if @train.current_station.present? %>
	<strong>На станции:</strong>	
	<%= @train.current_station.title %>
	<% else %>
	<p>Не находится на станции</p>
	<% end %>
</p>

<%= link_to 'Изменить', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>